In [89]:
import sys
sys.path.append('/home/wangs/rs/lwm/lib')
sys.path.append('/home/wangs/rs/lib')
import et
import ff
import numpy as np

In [90]:
def numsGame(nums):
    result=[]
    pa_1=np.array([])
    pa_2=0
    
    for i in range(len(nums)):
        pa_1=np.append(pa_1,nums[i]-0.5*i)
        pa_2=np.median(pa_1)
        median_offset = 0.5 if i % 2 != 0 else 0
        median_value = round(pa_2 + median_offset) - median_offset
        result.append(sum(abs(pa_1-median_value)))
        pa_1=pa_1+0.5
    return result

In [94]:
import heapq

heap = []
heapq.heappush(heap, 4)
heapq.heappush(heap, 1)


In [98]:

class Solution:
    def numsGame(self, nums):
        n = len(nums)
        res = [0] * n
        lower, upper = [], []
        lowerSum, upperSum = 0, 0
        mod = int(1e9 + 7)
        for i in range(n):
            x = nums[i] - i
            if len(lower) == 0 or -lower[0] >= x:
                lowerSum += x
                heapq.heappush(lower, -x)
                if len(lower) > len(upper) + 1:
                    upperSum -= lower[0]
                    heapq.heappush(upper, -lower[0])
                    lowerSum += heapq.heappop(lower)
            else:
                upperSum += x
                heapq.heappush(upper, x)
                if len(lower) < len(upper):
                    lowerSum += upper[0]
                    heapq.heappush(lower, -upper[0])
                    upperSum -= heapq.heappop(upper)
            if (i + 1) % 2 == 0:
                res[i] = (upperSum - lowerSum) % mod
            else:
                res[i] = (upperSum - lowerSum - lower[0]) % mod
        return res


In [99]:
# 创建 Solution 类的实例
solution_instance = Solution()

# 定义输入列表 nums
nums = [1, 23, 2, 3, 2, 4, 3, 43, 4, 54, 1]

# 调用 numsGame 方法并获取结果
result = solution_instance.numsGame(nums)

# 打印结果
print(result)


[0, 21, 22, 23, 25, 26, 29, 65, 69, 114, 123]


In [79]:
nums = [3,4,5,1,6,7]
numsGame(nums)

[0.0, 0.0, 0.0, 5.0, 6.0, 7.0]

In [56]:
a=np.array(nums)-1

In [57]:
np.append(a,1)

array([2, 3, 4, 0, 5, 6, 1])

In [30]:
nums[0:2]-np.linspace((i-1)/2,-(i-1)/2,i+1)

array([2.5, 4.5])

In [48]:
i=3
np.linspace(i/2,-i/2,i+1)

array([ 1.5,  0.5, -0.5, -1.5])